<?php

namespace FrontendBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * DatUrlRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DatUrlRepository extends EntityRepository
{
}
