<?php

namespace FrontendBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * NomDriverRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NomDriverRepository extends EntityRepository
{
    public function save(NomDriver $nomDriver)
    {
        $this->_em->persist($nomDriver);
        $this->_em->flush();
    }

    public function findById($id, array $orderBy = array())
    {
        if (empty($orderBy)) {
            $orderBy = ['name' => 'DESC'];
        }

        return $this->findBy(['id' => $id], $orderBy);
    }
}
