<?php

namespace UserBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * RoleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RoleRepository extends EntityRepository
{
    public function save(Role $role)
    {
        $this->_em->persist($role);
        $this->_em->flush();
    }

    public function findById($id, array $orderBy = array())
    {
        if (empty($orderBy)) {
            $orderBy = ['name' => 'DESC'];
        }

        return $this->findBy(['id' => $id], $orderBy);
    }

    public function delete($role){
        $this->_em->remove($role);
        $this->_em->flush();
    }
}
