parameters:

   rest.services.rest.class: RestBundle\Service\RestService
services:
#    rest.example:
#        class: RestBundle\Example
#        arguments: [@service_id, "plain_value", %parameter%]
    rest.tocken:
        class: %rest.services.rest.class%
    mycp.utils:
        class: RestBundle\Service\MyCpUtils