user_routes:
    resource: "@UserBundle/Controller/"
    type:     annotation

user_login:
    pattern:  /login
    defaults: { _controller: FOSUserBundle:Security:login }

user_login_check:
    pattern:  /login_check
    defaults: { _controller: FOSUserBundle:Security:check }

user_logout:
    path: fos_user_security_logout